# Generated by Django 4.2.2 on 2023-06-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Наименование активности"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Актуальная активность?"
                    ),
                ),
            ],
            options={
                "db_table": "Activities",
            },
        ),
        migrations.CreateModel(
            name="TGUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="ID пользователя"
                    ),
                ),
                ("chat_id", models.BigIntegerField(verbose_name="ID чата")),
                (
                    "username",
                    models.CharField(max_length=64, null=True, verbose_name="Никнейм"),
                ),
                ("balance", models.IntegerField(default=0, verbose_name="Баланс")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "data_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "db_table": "TGUser",
            },
        ),
        migrations.CreateModel(
            name="TrackedActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_time", models.TimeField(verbose_name="Время отслеживания")),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.activity",
                        verbose_name="Активность",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tguser",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "db_table": "TrackedActivities",
            },
        ),
    ]
