# Generated by Django 4.2.2 on 2023-06-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_message",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Наименования сообщения"
                    ),
                ),
                ("text_message", models.TextField(verbose_name="Текст сообщения")),
            ],
        ),
        migrations.CreateModel(
            name="TrackingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.IntegerField(verbose_name="Период отслеживания")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tguser",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
