# Generated by Django 4.2.2 on 2023-06-12 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_defaultmessage_trackingtime"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DefaultMessage",
        ),
        migrations.AlterModelTable(
            name="activity",
            table="Activity",
        ),
        migrations.AlterModelTable(
            name="trackedactivity",
            table="TrackedActivity",
        ),
        migrations.AlterModelTable(
            name="trackingtime",
            table="TrackingTime",
        ),
    ]
