# Generated by Django 4.2.2 on 2023-06-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_delete_defaultmessage_alter_activity_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackingtime",
            name="period",
            field=models.DateField(verbose_name="До какого числа отслеживается"),
        ),
    ]
