# Generated by Django 4.2.2 on 2023-07-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_trackingtime_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackingtime",
            name="mode",
            field=models.CharField(default="Hard", max_length=10, verbose_name="Режим"),
        ),
    ]
